### ISSUE TITLE
Please python3-pygments to the docker image

### ISSUE THREAD

**Issue by felipebalbi** [hspaans/latexmk-action#69]
**Is your feature request related to a problem? Please describe.**
If using `minted` for code listings, github actions will always fail due to missing `python3-pygments`

**Describe the solution you'd like**
Please add `python3-pygments` to the docker image generation

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by hspaans** [comment]
@felipebalbi could you please verify it all works for you now? The updated image is available in version 1.1.1.

**Comment by felipebalbi** [comment]
@hspaans Thanks, works perfectly. Closing the issue.
